from my_math import factorial

def main():
    try:
        number = int(input().strip())
        
        result = factorial(number)
        print(result)
        
    except ValueError as e:
        print(f"Ошибка: {e}")
    except TypeError as e:
        print(f"Ошибка: {e}")
    except Exception as e:
        print(f"Неизвестная ошибка: {e}")

if __name__ == "__main__":
    main()
